### ISSUE TITLE
improve display on mobile 

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/data-stories#112]
Lots of things need to be fixed, just look at it. There are texts overflowing their cards, pushed to the right by images that are too big and should be on top etc...

**Comment by valentinoli** [comment]
https://medium.com/@Vincentxia77/what-is-mobile-first-design-why-its-important-how-to-make-it-7d3cf2e29d00

**Comment by fquellec** [comment]
Done in [6606e8ea5d32f8fc5db5719d9bce0f9f7c482fb5](https://github.com/hestiaAI/data-stories/commit/6606e8ea5d32f8fc5db5719d9bce0f9f7c482fb5)
